"use client";

import * as Dialog from "@radix-ui/react-dialog";
import {useEffect,useState} from "react";
import {X} from "lucide-react";
import {Equipamento,Frete,Frota} from "@/features/pranchas/types";

type EditableFrete=Pick<Frete,"equipamentoTipo"|"origem"|"destino"|"motorista"|"frota"|"solicitante"|"responsavel"|"setor"|"observacao">;

export function EditFreteModal({frete,frotas,equipamentos:_,close,save}:{frete:Frete|null;frotas:Frota[];equipamentos:Equipamento[];close:()=>void;save:(data:EditableFrete)=>void}){
 const [data,setData]=useState<EditableFrete>({origem:"",destino:"",solicitante:"",responsavel:"",setor:"",observacao:""});
 useEffect(()=>{if(frete)setData({equipamentoTipo:[frete.equipamentoTipo,frete.equipamentoCodigo].filter(Boolean).join(" "),origem:frete.origem,destino:frete.destino,motorista:frete.motorista,frota:frete.frota,solicitante:frete.solicitante,responsavel:frete.responsavel,setor:frete.setor,observacao:frete.observacao})},[frete]);
 if(!frete)return null;
 const set=(field:keyof EditableFrete,value:string)=>setData(d=>({...d,[field]:value}));
 const valid=data.origem.trim()&&data.destino.trim()&&data.solicitante.trim()&&data.responsavel.trim()&&data.setor.trim();

 return <Dialog.Root open onOpenChange={v=>!v&&close()}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-[60] bg-black/35"/><Dialog.Content className="fixed left-1/2 top-1/2 z-[60] max-h-[90vh] w-[calc(100%-2rem)] max-w-2xl -translate-x-1/2 -translate-y-1/2 overflow-y-auto rounded-2xl bg-white shadow-2xl"><header className="sticky top-0 z-10 flex items-start justify-between border-b bg-white p-5"><div><Dialog.Title className="font-semibold">Editar Frete</Dialog.Title><Dialog.Description className="mt-1 text-xs text-[#748078]">Atualize os dados do frete {frete.id}</Dialog.Description></div><button onClick={close}><X size={19}/></button></header><div className="grid gap-4 p-5 sm:grid-cols-2"><label className="sm:col-span-2"><span className="label">Equipamento</span><input className="field" placeholder="Ex.: Pá Carregadeira 41002" value={data.equipamentoTipo||""} onChange={e=>set("equipamentoTipo",e.target.value)}/></label><label><span className="label">Origem</span><input className="field" value={data.origem} onChange={e=>set("origem",e.target.value)}/></label><label><span className="label">Destino</span><input className="field" value={data.destino} onChange={e=>set("destino",e.target.value)}/></label><label><span className="label">Frota</span><select className="field" value={data.frota||""} onChange={e=>set("frota",e.target.value)}><option value="">Sem frota</option>{frotas.filter(f=>f.status!=="Manutenção"&&(f.status==="Disponível"||f.numero===frete.frota)).map(f=><option key={f.numero} value={f.numero}>Frota {f.numero} · Prancha {f.prancha}</option>)}</select></label><label><span className="label">Motorista</span><input className="field" value={data.motorista||""} onChange={e=>set("motorista",e.target.value)}/></label><label><span className="label">Solicitante</span><input className="field" value={data.solicitante} onChange={e=>set("solicitante",e.target.value)}/></label><label><span className="label">Responsável da Logística</span><input className="field" value={data.responsavel} onChange={e=>set("responsavel",e.target.value)}/></label><label className="sm:col-span-2"><span className="label">Setor</span><input className="field" value={data.setor} onChange={e=>set("setor",e.target.value)}/></label><label className="sm:col-span-2"><span className="label">Observação</span><textarea className="field" rows={3} value={data.observacao} onChange={e=>set("observacao",e.target.value)}/></label><div className="flex gap-3 pt-2 sm:col-span-2"><button onClick={close} className="flex-1 rounded-xl border py-3 text-sm font-semibold">Cancelar</button><button disabled={!valid} onClick={()=>save(data)} className="flex-1 rounded-xl bg-[#174e37] py-3 text-sm font-semibold text-white disabled:opacity-40">Salvar Alterações</button></div></div></Dialog.Content></Dialog.Portal></Dialog.Root>
}
