"use client";

import {useEffect,useRef,useState} from "react";
import {ChevronUp,LogOut,UserRound} from "lucide-react";
import {createClient} from "@/lib/supabase/client";

export type AuthUser={name:string;email:string};

export function AccountMenu({user}:{user:AuthUser}){const [open,setOpen]=useState(false),[loading,setLoading]=useState(false),ref=useRef<HTMLDivElement>(null);useEffect(()=>{const close=(e:MouseEvent)=>{if(ref.current&&!ref.current.contains(e.target as Node))setOpen(false)};document.addEventListener("mousedown",close);return()=>document.removeEventListener("mousedown",close)},[]);const initials=user.name.split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase();const logout=async()=>{setLoading(true);try{await fetch("/api/auth/logout",{method:"POST"})}finally{window.location.replace("/login")}};return <div ref={ref} className="relative"><button onClick={()=>setOpen(v=>!v)} className="flex w-full items-center gap-3 rounded-xl border border-white/10 bg-white/[.04] p-3 text-left transition hover:bg-white/[.07]"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-[#d6f269] text-xs font-bold text-[#183527]">{initials||"U"}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{user.name}</p><p className="truncate text-[10px] text-white/45">{user.email}</p></div><ChevronUp size={14} className={`text-white/45 transition ${open?"rotate-0":"rotate-180"}`}/></button>{open&&<div className="absolute bottom-[calc(100%+8px)] left-0 w-full overflow-hidden rounded-xl border border-[#314239] bg-[#213029] p-1.5 shadow-2xl"><button className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-xs text-white/75 hover:bg-white/[.07]"><UserRound size={14}/>Meu Perfil</button><button disabled={loading} onClick={logout} className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-xs text-red-300 hover:bg-white/[.07] disabled:opacity-50"><LogOut size={14}/>{loading?"Saindo...":"Sair"}</button></div>}</div>}
